
controller_frequency: 10.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.05
   #max_vel_y: 0.0  # zero for a differential drive robot
   #min_vel_y: 0.0
   max_vel_theta: 0.3
   min_vel_theta: -0.3
   max_rotational_vel: 0.3
   min_in_place_vel_theta: 0.15
   min_in_place_rotational_vel: 0.15
   escape_vel: 0.0
   acc_lim_x: 2.5
   acc_lim_y: 0.1  # zero for a differential drive robot
   acc_lim_theta: 3.2
   #acc_lim_theta: 1.0

   holonomic_robot: false
   yaw_goal_tolerance: 0.5 # about 6 degrees
   xy_goal_tolerance: 0.2  # 1 cm
#   latch_xy_goal_tolerance: false
   pdist_scale: 0.8
   gdist_scale: 0.4
   occdist_scale: 0.01
   meter_scoring: true

   heading_lookahead: 0.325
#   heading_scoring: false
#   heading_scoring_timestep: 0.8
#   occdist_scale: 0.05
#   oscillation_reset_dist: 0.05
#   publish_cost_grid_pc: false
#   prune_plan: true

   sim_time: 2.0
   sim_granularity: 0.1
   angular_sim_granularity: 0.1
#   vx_samples: 8
#   vy_samples: 0  # zero for a differential drive robot
#   vtheta_samples: 20
#   dwa: true
#   simple_attractor: false

